### ISSUE TITLE
No copien código de mi repositorio si no se ha explicado.

### ISSUE THREAD

**Issue by frodriSanDocente** [chris-jmn96/PHP-practic-SKILLS_UP#1]
https://github.com/chris-jmn96/PHP-practic-SKILLS_UP/blob/294cf1ed4698db37e646edf956914766e7c41dd4/modules/include/new_reg.php#L146
¿Cómo es que tienes esto en tu código?, si no lo he explicado en clase. Asumiré que eres la mala influencia que afectó a Janet.

**Comment by chris-jmn96** [comment]
Corregido.
